### ISSUE TITLE
大佬 有群吗 

### ISSUE THREAD

**Issue by zeroT6** [Wislove/xddq-server#1]
之前大佬的库删了 方便创建个群吗

**Comment by Wislove** [comment]
没有群，随便弄的，之前大佬估计退坑了

**Comment by zhouerfu77322** [comment]
大佬说有人拿他代码去卖了，直接关项目，怕进去

**Comment by ChinaDragonNB** [comment]
大佬不更新，天塌了，我都还没学明白

**Comment by ChinaDragonNB** [comment]
他后面不应该出docker之类的部署的，大家本地跑跑就行了

**Comment by Wislove** [comment]
其他都还是不难，最难的是protobuf文件的获取，一直没找到在哪里

**Comment by zeroT6** [comment]
上午学写了一个ws反序列化 应该可以直接读到发送的参数  然后构建protoc文件格式

**Comment by ChinaDragonNB** [comment]
大佬们，建个群交流经验吧
