### ISSUE TITLE
刷新灵兽有bug

### ISSUE THREAD

**Issue by Pa55w0rd** [Wislove/xddq-server#2]
![image](https://github.com/user-attachments/assets/4e813f21-1993-4904-acc8-9b02af81fdf8)
刚下载的代码，有bug，刷到期望灵兽后，还继续刷新，建议刷到期望灵兽后任务暂停，或者增加一个开关是否购买

**Comment by zeroT6** [comment]
const hasWishPets = this.petPoolData.forEach(item => {
                if (this.wishPets.includes(item.petId) && item.isGet == false) {
                    logger.info(`[灵兽管理] 有期望灵兽未抓捕，不执行免费刷新, 期望灵兽: ${DBMgr.inst.getLanguageWord(`Items-${item.petId}`)}`);
                    return true;
                }
            });

**Comment by Wislove** [comment]
确实有bug，需要处理一下同步的问题
